"""Idempotent demo-data seeder, run once on API container startup (see app/main.py lifespan).

Creates a `demo@example.com` user with a realistic task history (generated by the same
`simulate_backlog` process used for ML training/evaluation) so a fresh `docker compose up` has
real data to explore immediately: a history of completed tasks (for the ranker to have been
"informed" by, conceptually) and a live open backlog for /recommendations/next-tasks to rank.
"""
from __future__ import annotations

import logging

from sqlalchemy.orm import Session

from app.core.security import hash_password
from app.ml.generator import simulate_backlog
from app.models.models import Interaction, Task, User

logger = logging.getLogger("tasks.seed")

DEMO_EMAIL = "demo@example.com"
DEMO_PASSWORD = "demo12345"


def seed_demo_user(db: Session) -> None:
    existing = db.query(User).filter(User.email == DEMO_EMAIL).first()
    if existing is not None:
        return

    logger.info("Seeding demo user with synthetic task history")
    user = User(email=DEMO_EMAIL, password_hash=hash_password(DEMO_PASSWORD), sync_version=0)
    db.add(user)
    db.flush()

    tasks = simulate_backlog(n_tasks=200, seed=7)
    tasks_by_completion = sorted(tasks, key=lambda t: t.completion_rank)
    history = tasks_by_completion[:150]
    open_backlog = tasks_by_completion[150:]

    version = 0
    for t in history:
        version += 1
        task = Task(
            user_id=user.id,
            title=f"{t.category.title()} task ({t.priority})",
            description=f"Synthetic seeded task, priority={t.priority}",
            priority=t.priority,
            category=t.category,
            status="completed",
            due_date=t.due_date,
            estimated_minutes=t.estimated_minutes,
            completed_at=t.completed_at,
            sync_version=version,
            created_at=t.created_at,
            updated_at=t.completed_at,
        )
        db.add(task)
        db.flush()
        db.add(Interaction(user_id=user.id, task_id=task.id, event_type="created", occurred_at=t.created_at))
        db.add(Interaction(user_id=user.id, task_id=task.id, event_type="completed", occurred_at=t.completed_at))

    for t in open_backlog:
        version += 1
        task = Task(
            user_id=user.id,
            title=f"{t.category.title()} task ({t.priority})",
            description=f"Synthetic seeded task, priority={t.priority}",
            priority=t.priority,
            category=t.category,
            status="pending",
            due_date=t.due_date,
            estimated_minutes=t.estimated_minutes,
            sync_version=version,
            created_at=t.created_at,
            updated_at=t.created_at,
        )
        db.add(task)
        db.flush()
        db.add(Interaction(user_id=user.id, task_id=task.id, event_type="created", occurred_at=t.created_at))

    user.sync_version = version
    db.commit()
    logger.info("Seeded %d completed + %d open demo tasks", len(history), len(open_backlog))
